name: marketnpos
favicon: null
layout_spectrum: 0.7689152474049479
typography_spectrum: 0.5469852031674236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2936039969790727
  lightness: 0.6568107637576759
  saturation: 0.17243963130749762
  rhythmicContrast: 0.26624102517962456
purpose: []
